# Generated by Django 3.2.9 on 2023-11-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20231107_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
