# Generated by Django 3.2.9 on 2023-11-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Course'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(null=True, to='courses.Category'),
        ),
    ]
